name: CI/CD to Docker Hub

on:
  push:
    branches: [ "deployment" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t widhofaisal/backend-golang:latest .
        
      - name: Push Docker image
        run: docker push widhofaisal/backend-golang:latest
